apiVersion: v1
kind: Service
metadata:
  name: hive
  namespace: hive
  labels:
    app.kubernetes.io/name: hive
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hive
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
