# External Secrets controller'ı IRSA ile Secrets Manager'a erişir (izin sadece chem-hive/db).
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
