apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: hive
    newName: 417732881703.dkr.ecr.eu-central-1.amazonaws.com/chem-hive
    newTag: latest
